Wed Jan 15 13:19:58 EST 2025
c1006a-s11.ufhpc
/blue/hmedeiros/moralesmurallesm/PruebaAlphaFold
INFO:    underlay of /usr/bin/nvidia-cuda-mps-control required more than 50 (335) bind mounts
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Read-only file system
I0115 13:20:06.153555 23454871533376 templates.py:857] Using precomputed obsolete pdbs /data/reference/alphafold/2.3.2/pdb_mmcif/obsolete.dat.
I0115 13:20:07.115971 23454871533376 xla_bridge.py:353] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
I0115 13:20:08.018009 23454871533376 xla_bridge.py:353] Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: Interpreter Host CUDA
I0115 13:20:08.018420 23454871533376 xla_bridge.py:353] Unable to initialize backend 'tpu': module 'jaxlib.xla_extension' has no attribute 'get_tpu_client'
I0115 13:20:08.018494 23454871533376 xla_bridge.py:353] Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
I0115 13:20:13.950729 23454871533376 run_alphafold.py:424] Have 5 models: ['model_1_pred_0', 'model_2_pred_0', 'model_3_pred_0', 'model_4_pred_0', 'model_5_pred_0']
I0115 13:20:13.950993 23454871533376 run_alphafold.py:438] Using random seed 1381408563660920048 for the data pipeline
I0115 13:20:13.951181 23454871533376 run_alphafold.py:185] Predicting uniprotkb_2024_12_04.fasta
Traceback (most recent call last):
  File "/app/alphafold/run_alphafold.py", line 468, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/app/alphafold/run_alphafold.py", line 443, in main
    predict_structure(
  File "/app/alphafold/run_alphafold.py", line 189, in predict_structure
    os.makedirs(output_dir)
  File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 2 more times]
  File "/opt/conda/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '~'
Wed Jan 15 13:20:20 EST 2025
